### ISSUE TITLE
(URGENT) Build fails at `spec` file when a specified image is missing, or an additional image is not listed

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/jekyll-theme-open-project-helpers#21]
e.g. 
https://github.com/metanorma/metanorma.org/runs/3279098951?check_suite_focus=true

```
/opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/spec_builders/png_diagrams.rb:72:in `block in build_spec_pages': Navigation item matching StandardDoc_Form.png (specs/metanorma-model-standoc) was not found (RuntimeError)
26
```

This problem has consumed numerous (at least a dozen) hours of @opoudjis and my time in tweaking the source index. We need to ensure:

1. If there is a specified image but it doesn't exist, raise an error but DO NOT CRASH.
2. If there is an image that was not specified but it exists, DO NOT RAISE ANY ERROR. This is expected to not fail.

**Comment by CAMOBAP** [comment]
In progress

**Comment by CAMOBAP** [comment]
1. [x] changed to raise a warning
2. [ ] in progress

**Comment by CAMOBAP** [comment]
@ronaldtse I have no permission to release the gem. Version increased and pushed to the repo

**Comment by ronaldtse** [comment]
@camobap the gem is now released. I had to also update+release jekyll-theme-open-project to use this new version. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP I've added the `RIBOSE_RUBYGEMS_API_KEY` secret here for releasing the gem, could you help update the GHA CI? Thanks!
