### ISSUE TITLE
Add GHA workflow to auto-release gem

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/jekyll-theme-open-project-helpers#23]
We want to automatically release the gem when a new version is tagged. 

The Rubygems API token is provided at the secret named `RIBOSE_RUBYGEMS_API_KEY`.

_Originally posted by @ronaldtse in https://github.com/riboseinc/jekyll-theme-open-project-helpers/issues/21#issuecomment-895701322_

**Comment by CAMOBAP** [comment]
@ronaldtse I have added two simple tests and both rake and release workflow, unfortunately, GHA doesn't work at all IDK why.

There is nothing unique for this repo.

Could you please check that GHA enabled for this repo?

**Comment by ronaldtse** [comment]
@CAMOBAP yes it is enabled, very strange. I just manually ran it once.

**Comment by CAMOBAP** [comment]
Initially, I wasn't able to trigger it even with `workflow_dispatch` now it looks working

**Comment by ronaldtse** [comment]
Great, thanks.
